# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59b489e334c0bee84a9d370013ddfb4e994836dbbaf9ee3d01ce062a3cc6d9a3c2a8e4714567dc8e909e06214e2cf912d615351db43dceb76c5510a9ae7f6e6

test:
  secret_key_base: 9cba9dd176b75bd5b5a38babdbd5dd35594cc57d2b39cb142edf5527f2dd14c2b7618ae71c937b23e8878b684b8c7812497d2a66bb3127b9afa891a0690f7c68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
